#!/usr/bin/env bash
# Regenerates internal/resources/allowlist_test.go from terraform-provider-opnsense's
# actual resource/data-source TypeName strings, so grimoire never emits HCL
# for a resource type the provider can't ingest.
set -euo pipefail

REPO_URL="https://github.com/browningluke/terraform-provider-opnsense.git"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/internal/resources/allowlist_test.go"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git clone --depth 1 --quiet "$REPO_URL" "$TMP/provider"

types="$(grep -rhoE 'ProviderTypeName \+ "_[a-z0-9_]+"' "$TMP/provider/internal/service/" \
  | sed -E 's/.*"(_[a-z0-9_]+)"/opnsense\1/' \
  | sort -u)"

{
  echo "// Code generated by 'task update-allowlist'. DO NOT EDIT."
  echo "// Source: https://github.com/browningluke/terraform-provider-opnsense/tree/master/internal/service"
  echo
  echo "package resources"
  echo
  echo "// validTFTypes are the resource/data-source types terraform-provider-opnsense"
  echo "// implements. Grimoire must never emit HCL for a type not in this list —"
  echo "// regenerate with 'task update-allowlist' after the provider adds resources."
  echo "var validTFTypes = map[string]bool{"
  while IFS= read -r t; do
    [ -n "$t" ] && printf '\t"%s": true,\n' "$t"
  done <<<"$types"
  echo "}"
} >"$OUT"

gofmt -w "$OUT"
echo "updated $OUT ($(echo "$types" | grep -c .) types)"
